name: Deploy to Netlify

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  Deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Publish to Netlify
        id: deployment
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: 'npm install -g netlify-cli && netlify deploy --build --prod'
