name: Deploy to Fly.io

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: server

jobs:
  Deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions@master

      - name: Publish to Fly.io
        run: 'flyctl deploy --remote-only'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
