name: Deploy to Netlify

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ steps.deployment.outputs.deploy-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Build bundle
        run: npm run build

      - name: Publish to Netlify
        id: deployment
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './client/dist'
          production-deploy: true
          functions-dir: './client/src'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
